// preguntas.js
const bancoPreguntas = [
    { pregunta: "¿Qué componente es el cerebro de la computadora?", opciones: ["RAM", "CPU", "Disco duro", "Monitor"], respuesta: "CPU" },
    { pregunta: "¿Cuál es un sistema operativo?", opciones: ["Microsoft Word", "Windows", "Chrome", "Google"], respuesta: "Windows" },
    { pregunta: "¿Qué tipo de software es Excel?", opciones: ["Navegador", "Antivirus", "Ofimática", "Sistema operativo"], respuesta: "Ofimática" },
    { pregunta: "¿Qué significa WWW?", opciones: ["World Wide Web", "Windows Web World", "Web Without Wires", "Wireless World Web"], respuesta: "World Wide Web" },
    { pregunta: "¿Qué es un archivo .jpg?", opciones: ["Archivo de video", "Imagen", "Documento", "Audio"], respuesta: "Imagen" },
    { pregunta: "¿Qué puerto se usa para conectar USB?", opciones: ["HDMI", "RJ45", "USB", "VGA"], respuesta: "USB" },
    { pregunta: "¿Cuál es la unidad básica de almacenamiento?", opciones: ["Bit", "Pixel", "Mega", "Chip"], respuesta: "Bit" },
    { pregunta: "¿Cuál es un ejemplo de hardware?", opciones: ["Photoshop", "CPU", "Windows", "Excel"], respuesta: "CPU" },
    { pregunta: "¿Qué es phishing?", opciones: ["Robo de identidad", "Virus de audio", "Hackeo de red", "Espionaje digital"], respuesta: "Robo de identidad" },
    { pregunta: "¿Qué navegador es desarrollado por Google?", opciones: ["Safari", "Firefox", "Chrome", "Opera"], respuesta: "Chrome" },
    { pregunta: "¿Cuál es la función del router?", opciones: ["Imprimir", "Conectar dispositivos a internet", "Almacenar archivos", "Reproducir sonido"], respuesta: "Conectar dispositivos a internet" },
    { pregunta: "¿Qué extensión pertenece a un documento Word?", opciones: [".xls", ".jpg", ".docx", ".mp3"], respuesta: ".docx" },
    { pregunta: "¿Qué dispositivo sirve para ingresar texto?", opciones: ["Monitor", "Ratón", "Teclado", "CPU"], respuesta: "Teclado" },
    { pregunta: "¿Qué es la nube en informática?", opciones: ["Un virus", "Almacenamiento remoto", "Software espía", "Sistema de sonido"], respuesta: "Almacenamiento remoto" },
    { pregunta: "¿Qué red social es para compartir imágenes?", opciones: ["WhatsApp", "Instagram", "Spotify", "Dropbox"], respuesta: "Instagram" },
    { pregunta: "¿Qué aplicación se usa para presentaciones?", opciones: ["PowerPoint", "Excel", "Word", "Paint"], respuesta: "PowerPoint" },
    { pregunta: "¿Cuál es un sistema de almacenamiento portátil?", opciones: ["Nube", "Pendrive", "Monitor", "Teclado"], respuesta: "Pendrive" },
    { pregunta: "¿Qué es un antivirus?", opciones: ["Software malicioso", "Software para proteger", "Hardware externo", "Sistema de red"], respuesta: "Software para proteger" },
    { pregunta: "¿Qué extensión tiene un archivo de audio?", opciones: [".docx", ".jpg", ".mp3", ".pdf"], respuesta: ".mp3" },
    { pregunta: "¿Cuál de estos es un navegador web?", opciones: ["Google Docs", "Edge", "Windows", "Android"], respuesta: "Edge" },
    { pregunta: "¿Qué es un pixel?", opciones: ["Unidad de texto", "Unidad de imagen", "Unidad de red", "Unidad de sonido"], respuesta: "Unidad de imagen" },
    { pregunta: "¿Qué tipo de memoria almacena datos temporalmente?", opciones: ["ROM", "RAM", "Disco duro", "USB"], respuesta: "RAM" },
    { pregunta: "¿Qué programa sirve para editar fotos?", opciones: ["Word", "Excel", "Photoshop", "PowerPoint"], respuesta: "Photoshop" },
    { pregunta: "¿Qué es una red LAN?", opciones: ["Red local", "Red mundial", "Red inalámbrica", "Red social"], respuesta: "Red local" },
    { pregunta: "¿Qué es una IP?", opciones: ["Número de red", "Disco externo", "Software", "Tipo de conexión"], respuesta: "Número de red" },
    { pregunta: "¿Qué dispositivo convierte energía eléctrica en sonido?", opciones: ["Micrófono", "Altavoz", "USB", "CD"], respuesta: "Altavoz" },
    { pregunta: "¿Qué empresa creó Windows?", opciones: ["Apple", "Linux", "Microsoft", "Google"], respuesta: "Microsoft" },
    { pregunta: "¿Cuál es la función del mouse?", opciones: ["Escribir", "Mover el cursor", "Almacenar archivos", "Reproducir videos"], respuesta: "Mover el cursor" },
    { pregunta: "¿Qué significa URL?", opciones: ["Universal Resource Link", "Uniform Resource Locator", "Universal Router Language", "User Request List"], respuesta: "Uniform Resource Locator" },
    { pregunta: "¿Cuál de estos es un sistema de almacenamiento?", opciones: ["RAM", "CPU", "Disco duro", "GPU"], respuesta: "Disco duro" },
    { pregunta: "¿Cuál es una amenaza informática?", opciones: ["CPU", "WiFi", "Malware", "Bluetooth"], respuesta: "Malware" },
    { pregunta: "¿Qué es el HTML?", opciones: ["Lenguaje de programación", "Lenguaje de marcado", "Sistema operativo", "Antivirus"], respuesta: "Lenguaje de marcado" },
    { pregunta: "¿Cuál es un dispositivo de entrada?", opciones: ["Pantalla", "Monitor", "Ratón", "Altavoz"], respuesta: "Ratón" },
    { pregunta: "¿Qué es el software?", opciones: ["Parte física", "Parte lógica", "Periférico", "Red"], respuesta: "Parte lógica" },
    { pregunta: "¿Qué se necesita para acceder a Internet?", opciones: ["Router", "Teclado", "Mouse", "Disco duro"], respuesta: "Router" },
    { pregunta: "¿Qué es un sistema operativo?", opciones: ["Software de base", "Software de red", "Aplicación", "Hardware"], respuesta: "Software de base" },
    { pregunta: "¿Qué empresa desarrolla Android?", opciones: ["Apple", "Samsung", "Google", "Microsoft"], respuesta: "Google" },
    { pregunta: "¿Cuál de estos es un archivo de video?", opciones: [".png", ".mp4", ".pdf", ".exe"], respuesta: ".mp4" },
    { pregunta: "¿Qué componente permite ver la información?", opciones: ["Mouse", "Monitor", "Teclado", "Parlante"], respuesta: "Monitor" },
    { pregunta: "¿Qué significa CPU?", opciones: ["Central Process Unit", "Computer Primary Unit", "Central Processing Unit", "Computer Power Utility"], respuesta: "Central Processing Unit" },
    { pregunta: "¿Qué extensión tiene un archivo Excel?", opciones: [".ppt", ".docx", ".xls", ".mp3"], respuesta: ".xls" },
    { pregunta: "¿Qué se considera una buena práctica digital?", opciones: ["Compartir contraseñas", "Hacer clic en cualquier enlace", "Actualizar software", "Ignorar antivirus"], respuesta: "Actualizar software" },
    { pregunta: "¿Qué herramienta permite navegar en la red?", opciones: ["Word", "Chrome", "Excel", "Paint"], respuesta: "Chrome" },
    { pregunta: "¿Qué significa USB?", opciones: ["Universal Serial Bus", "Unique Software Base", "User Serial Byte", "Utility Standard Base"], respuesta: "Universal Serial Bus" },
    { pregunta: "¿Qué dispositivo se usa para escuchar sonido?", opciones: ["Mouse", "Teclado", "Audífonos", "Monitor"], respuesta: "Audífonos" },
    { pregunta: "¿Qué es un firewall?", opciones: ["Protección contra virus", "Software de sonido", "Editor de video", "Base de datos"], respuesta: "Protección contra virus" },
    { pregunta: "¿Qué acción protege tus cuentas?", opciones: ["Contraseña débil", "Autenticación de dos pasos", "Usar WiFi público", "No cerrar sesión"], respuesta: "Autenticación de dos pasos" },
    { pregunta: "¿Qué es la ingeniería social?", opciones: ["Tipo de software", "Método para engañar usuarios", "Hardware", "Red de computadoras"], respuesta: "Método para engañar usuarios" },
    { pregunta: "¿Cuál es una buena medida de seguridad?", opciones: ["Compartir datos personales", "Tener antivirus", "Desactivar firewall", "Descargar cualquier archivo"], respuesta: "Tener antivirus" },
  ];
  